[[redirects]]
# KCSS Profiles
  from = "https://kcss.tk/p/killer21"
  to = "kcss.tk/p/killer21.html"
  status = 301

[[redirects]]
# KCSS Profiles
  from = "https://kcss.tk/p/Killer21"
  to = "kcss.tk/p/killer21.html"
  status = 301
